/* 테이블 생성 */
--1. 회원가입 테이블
CREATE TABLE MEMBER_TBL(
	MEM_ID					VARCHAR2(15)					CONSTRAINT PK_MEMBER_ID PRIMARY KEY,
	MEM_NAME             	VARCHAR2(30)					NOT NULL,
	MEM_PW                 	CHAR(60)					    NOT NULL,
	MEM_EMAIL            	VARCHAR2(50)					NOT NULL,
	MEM_ZIPCODE         	CHAR(5) 						NOT NULL,
	MEM_ADDR              	VARCHAR2(100)					NOT NULL,
	MEM_ADDR_D			    VARCHAR2(100)					NOT NULL,
	MEM_PHONE          	    VARCHAR2(15)					NOT NULL,
	MEM_NICK             	VARCHAR2(20)					NOT NULL UNIQUE,
	MEM_ACCEPT_E      	    CHAR(1)  DEFAULT 'Y'			NOT NULL,
	MEM_POINT				NUMBER DEFAULT 0          	 	NOT NULL,
	MEM_DATE_SUB      	    DATE  DEFAULT SYSDATE   		NOT NULL,
	MEM_DATE_UP        	    DATE  DEFAULT SYSDATE		    NOT NULL,  
	MEM_DATE_LAST   	    DATE  DEFAULT SYSDATE    		NOT NULL,
	MEM_AUTHCODE		    CHAR(1) DEFAULT 'N'				NOT NULL
	--MEM_SESSION_KEY	        VARCHAR2(50)
	--MEM_SESSION_LIMIT	TIMESTAMP
);
--2. 카테고리 테이블. BOM구조.
CREATE TABLE CATEGORY_TBL (
    CATE_CODE       			NUMBER        				    PRIMARY KEY,
    CATE_CODE_PRT     		    NUMBER,                                          
    CATE_NAME           		VARCHAR2(50)         			NOT NULL
);

-- CATE_CODE, CATE_CODE_PRT, CATE_NAME

INSERT INTO CATEGORY_TBL(CATE_CODE, CATE_CODE_PRT, CATE_NAME) VALUES(1, NULL, 'TOP');
INSERT INTO CATEGORY_TBL(CATE_CODE, CATE_CODE_PRT, CATE_NAME) VALUES(10, 1, '맨투맨/후드티');
INSERT INTO CATEGORY_TBL(CATE_CODE, CATE_CODE_PRT, CATE_NAME) VALUES(11, 1, '니트');
INSERT INTO CATEGORY_TBL(CATE_CODE, CATE_CODE_PRT, CATE_NAME) VALUES(12, 1, '긴팔티');
INSERT INTO CATEGORY_TBL(CATE_CODE, CATE_CODE_PRT, CATE_NAME) VALUES(13, 1, '반팔티');


INSERT INTO CATEGORY_TBL(CATE_CODE, CATE_CODE_PRT, CATE_NAME) VALUES(2, NULL, 'SHIRTS');
INSERT INTO CATEGORY_TBL(CATE_CODE, CATE_CODE_PRT, CATE_NAME) VALUES(20, 2, '베이직');
INSERT INTO CATEGORY_TBL(CATE_CODE, CATE_CODE_PRT, CATE_NAME) VALUES(21, 2, '청남방');
INSERT INTO CATEGORY_TBL(CATE_CODE, CATE_CODE_PRT, CATE_NAME) VALUES(22, 2, '체크/패턴');
INSERT INTO CATEGORY_TBL(CATE_CODE, CATE_CODE_PRT, CATE_NAME) VALUES(23, 2, '스트라이프');

INSERT INTO CATEGORY_TBL(CATE_CODE, CATE_CODE_PRT, CATE_NAME) VALUES(3, NULL, 'PANTS');
INSERT INTO CATEGORY_TBL(CATE_CODE, CATE_CODE_PRT, CATE_NAME) VALUES(30, 3, '슬랙스');
INSERT INTO CATEGORY_TBL(CATE_CODE, CATE_CODE_PRT, CATE_NAME) VALUES(31, 3, '면바지');
INSERT INTO CATEGORY_TBL(CATE_CODE, CATE_CODE_PRT, CATE_NAME) VALUES(32, 3, '청바지');
INSERT INTO CATEGORY_TBL(CATE_CODE, CATE_CODE_PRT, CATE_NAME) VALUES(33, 3, '밴딩팬츠');

INSERT INTO CATEGORY_TBL(CATE_CODE, CATE_CODE_PRT, CATE_NAME) VALUES(4, NULL, 'OUTER');
INSERT INTO CATEGORY_TBL(CATE_CODE, CATE_CODE_PRT, CATE_NAME) VALUES(40, 4, '패딩');
INSERT INTO CATEGORY_TBL(CATE_CODE, CATE_CODE_PRT, CATE_NAME) VALUES(41, 4, '코트');
INSERT INTO CATEGORY_TBL(CATE_CODE, CATE_CODE_PRT, CATE_NAME) VALUES(42, 4, '수트/블레이져');
INSERT INTO CATEGORY_TBL(CATE_CODE, CATE_CODE_PRT, CATE_NAME) VALUES(43, 4, '자켓');

INSERT INTO CATEGORY_TBL(CATE_CODE, CATE_CODE_PRT, CATE_NAME) VALUES(5, NULL, 'SHOES/BAG');
INSERT INTO CATEGORY_TBL(CATE_CODE, CATE_CODE_PRT, CATE_NAME) VALUES(50, 5, '신발');
INSERT INTO CATEGORY_TBL(CATE_CODE, CATE_CODE_PRT, CATE_NAME) VALUES(51, 5, '가방');


commit;

-- 1차카테고리
SELECT * FROM CATEGORY_TBL WHERE CATE_CODE_PRT IS NULL;

-- 1차 카테고리를 선택. 해당 2차카테고리
SELECT * FROM CATEGORY_TBL WHERE CATE_CODE_PRT = 1;


--3. 상품 테이블
DROP TABLE PRODUCT_TBL;

CREATE TABLE PRODUCT_TBL(
    PDT_NUM					NUMBER								CONSTRAINT PK_PRODUCT_NUM PRIMARY KEY, 
    CATE_CODE       		NUMBER          					NOT NULL,
    CATE_CODE_PRT       	NUMBER          					NOT NULL,
    PDT_NAME				VARCHAR2(50)						NOT NULL,
    PDT_PRICE				NUMBER								NOT NULL,
    PDT_DISCOUNT			NUMBER								NOT NULL,
    PDT_COMPANY			    VARCHAR2(30)						NOT NULL,
    PDT_DETAIL				VARCHAR2(4000)  /* CLOB */		    NOT NULL,
    PDT_IMG_FOLDER			VARCHAR2(100)						NOT NULL,
    PDT_IMG					VARCHAR2(100)						NOT NULL,
    PDT_AMOUNT			    NUMBER								NOT NULL,
    PDT_BUY					CHAR(1)	DEFAULT 'Y'                 NOT NULL,
    PDT_DATE_SUB			DATE DEFAULT SYSDATE                NOT NULL,
    PDT_DATE_UP			    DATE DEFAULT SYSDATE			    NOT NULL
);


-- PDT_NUM, CATE_CODE, CATE_CODE_PRT, PDT_NAME, PDT_PRICE, PDT_DISCOUNT, PDT_COMPANY, PDT_DETAIL, PDT_IMG_FOLDER, PDT_IMG, PDT_AMOUNT, PDT_BUY, PDT_DATE_SUB, PDT_DATE_UP

-- 상품테이블 시퀀스
CREATE SEQUENCE SEQ_PRODUCT_NUM;


--4. 장바구니 테이블 
CREATE TABLE CART_TBL(
	CART_CODE			NUMBER								PRIMARY KEY,			
	PDT_NUM				NUMBER								NOT NULL,
	MEM_ID				VARCHAR2(15)						NOT NULL,
	CART_AMOUNT			NUMBER								NOT NULL
);

-- CART_CODE, PDT_NUM, MEM_ID, CART_AMOUNT

-- 장바구니 시퀀스
CREATE SEQUENCE SEQ_CART_CODE;


--5. 주문 테이블 : 주문자와 배송지의 정보
CREATE TABLE ORDER_TBL(
	ODR_CODE			NUMBER								CONSTRAINT PK_ORDER_CODE PRIMARY KEY,
	MEM_ID				VARCHAR2(15)						NOT NULL,
	ODR_NAME			VARCHAR2(30)						NOT NULL,
	ODR_ZIPCODE			CHAR(5)								NOT NULL,
	ODR_ADDR			VARCHAR2(50)						NOT NULL,
	ODR_ADDR_D			VARCHAR2(50)						NOT NULL,
	ODR_PHONE			VARCHAR2(20)						NOT NULL,
	ODR_TOTAL_PRICE		NUMBER								NOT NULL,
	ODR_DATE			DATE DEFAULT SYSDATE			    NOT NULL
);

-- ODR_CODE, MEM_ID, ODR_NAME, ODR_ZIPCODE, ODR_ADDR, ODR_ADDR_D, ODR_PHONE, ODR_TOTAL_PRICE, ODR_DATE

--6. 주문 상세 테이블 : 주문상품 정보
CREATE TABLE ORDER_DETAIL_TBL(
	ODR_CODE			NUMBER								NOT NULL,
	PDT_NUM				NUMBER								NOT NULL,
	ODR_AMOUNT			NUMBER								NOT NULL,
	ODR_PRICE			NUMBER								NOT NULL,
	PRIMARY KEY (ODR_CODE, PDT_NUM) -- 복합키
);

-- ODR_CODE, PDT_NUM, ODR_AMOUNT, ODR_PRICE

/*
pay_code, odr_code, pay_method, pay_date, pay_tot_price, pay_rest_price, pay_nobank_user, pay_nobank

*/

-- 주문번호
CREATE SEQUENCE SEQ_ORD_CODE;

-- 결제정보 테이블
DROP TABLE PAYMENT_TBL;
CREATE TABLE PAYMENT_TBL (
    PAY_CODE  NUMBER    CONSTRAINT   PK_PAYMENT_CODE    PRIMARY KEY,
    ODR_CODE  NUMBER NOT NULL,
    PAY_METHOD VARCHAR2(30) NOT NULL,
    PAY_DATE DATE DEFAULT SYSDATE,
    PAY_TOT_PRICE NUMBER NOT NULL,
    PAY_REST_PRICE NUMBER NULL,
    PAY_NOBANK_USER VARCHAR2(20)    NULL,
    PAY_NOBANK  VARCHAR2(20)    NULL
);

-- PAY_CODE, ODR_CODE, PAY_METHOD, PAY_DATE, PAY_TOT_PRICE
-- 결제번호
CREATE SEQUENCE SEQ_PAYMENT_CODE;


--7. 게시판 테이블 
CREATE TABLE BOARD_TBL(
	BRD_NUM				NUMBER								CONSTRAINT PK_BOARD_NUM PRIMARY KEY, 
	MEM_ID				VARCHAR2(15)						NOT NULL,
	BRD_TITLE			VARCHAR2(100)						NOT NULL,
	BRD_CONTENT			VARCHAR2(4000)					    NOT NULL,
	BRD_DATE_REG		DATE DEFAULT SYSDATE			    NOT NULL
);
--8. 상품후기 테이블 
CREATE TABLE REVIEW_TBL(
	RV_NUM				NUMBER								CONSTRAINT PK_REVIEW_NUM PRIMARY KEY, 
	MEM_ID				VARCHAR2(15)						NOT NULL,
	PDT_NUM				NUMBER								NOT NULL,
	RV_CONTENT			VARCHAR2(200)						NOT NULL,
	RV_SCORE			NUMBER								NOT NULL,
	RV_DATE_REG			DATE DEFAULT SYSDATE			    NOT NULL
);

-- RV_NUM, MEM_ID, PDT_NUM, RV_CONTENT, RV_SCORE, RV_DATE_REG

CREATE SEQUENCE SEQ_REVIEW_NUM;



--9. 관리자 로그인 테이블
CREATE TABLE ADMIN_TBL(
	ADMIN_ID			VARCHAR2(15)						PRIMARY KEY,
	ADMIN_PW			CHAR(60)						    NOT NULL,
	ADMIN_NAME			VARCHAR2(15)						NOT NULL,
	ADMIN_DATE_LATE	    DATE DEFAULT	SYSDATE			    NOT NULL
);